"""Dataset loading + cleaning.

The source CSV (`_alerts_snapshot.csv`) is generated by the rule-based scanner
in the private `trading-algoritmico` repo. It contains one row per alert with
vote breakdown and a binary result (WIN/LOSS) computed by the next-candle close.

Known issue (documented 2026-05-21): the bot ran 24/7 and the data feed served
extrapolated candles on weekends, leaving 217 Sat/Sun rows that must be
removed before training.
"""
from __future__ import annotations

from pathlib import Path
from typing import NamedTuple

import numpy as np
import pandas as pd


class TemporalSplit(NamedTuple):
    train: pd.DataFrame
    val: pd.DataFrame
    test: pd.DataFrame


REQUIRED_COLUMNS = {
    "id",
    "timestamp",
    "symbol",
    "direction",
    "score",
    "regime",
    "adx",
    "atr",
    "vote_ema_dir",
    "vote_ema200",
    "vote_macd_mom",
    "vote_rsi7",
    "vote_bb",
    "vote_stoch",
    "vote_vol",
    "result",
}


def load_snapshot(csv_path: str | Path) -> pd.DataFrame:
    """Read the snapshot CSV, parse timestamps, drop unresolved rows."""
    df = pd.read_csv(csv_path)
    missing = REQUIRED_COLUMNS - set(df.columns)
    if missing:
        raise ValueError(f"missing required columns: {sorted(missing)}")
    df["timestamp"] = pd.to_datetime(df["timestamp"], utc=True, errors="coerce")
    df = df.dropna(subset=["timestamp", "result"])
    df = df[df["result"].isin(["WIN", "LOSS"])].copy()
    df = df.sort_values("timestamp").reset_index(drop=True)
    return df


def filter_weekend(df: pd.DataFrame) -> pd.DataFrame:
    """Remove Sat/Sun rows. Forex is closed; these come from a feed bug."""
    mask = df["timestamp"].dt.dayofweek < 5
    return df.loc[mask].reset_index(drop=True)


def temporal_split(
    df: pd.DataFrame,
    train_frac: float = 0.6,
    val_frac: float = 0.2,
) -> TemporalSplit:
    """Strict temporal split — no shuffling. test_frac = 1 - train - val."""
    if not 0 < train_frac < 1 or not 0 < val_frac < 1 or train_frac + val_frac >= 1:
        raise ValueError("invalid fractions")
    df = df.sort_values("timestamp").reset_index(drop=True)
    n = len(df)
    i_train = int(n * train_frac)
    i_val = int(n * (train_frac + val_frac))
    return TemporalSplit(
        train=df.iloc[:i_train].copy(),
        val=df.iloc[i_train:i_val].copy(),
        test=df.iloc[i_val:].copy(),
    )


def make_target(df: pd.DataFrame) -> np.ndarray:
    """WIN -> 1, LOSS -> 0."""
    return (df["result"].values == "WIN").astype(int)
